<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the users and refresh_tokens tables for JWT authentication';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration targets PostgreSQL.');

        $this->addSql(<<<'SQL'
            CREATE TABLE users (
                id       UUID PRIMARY KEY,
                email    VARCHAR(180) NOT NULL,
                password VARCHAR(255) NOT NULL,
                roles    JSON NOT NULL,
                CONSTRAINT uniq_users_email UNIQUE (email)
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE refresh_tokens (
                id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                refresh_token VARCHAR(128) NOT NULL,
                username      VARCHAR(255) NOT NULL,
                valid         TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                CONSTRAINT uniq_refresh_tokens_token UNIQUE (refresh_token)
            )
            SQL);

        $this->addSql('CREATE INDEX idx_refresh_tokens_username ON refresh_tokens (username)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE users');
    }
}